name: WPE
version: "0.2"
license: "GPL-2.0-or-later"
date: 2021-11-05
description: |
    Provides efficient methods for working with generic wreath products.

authors:
    - name: Friedrich Rober
      url: mailto:friedrich.rober@rwth-aachen.de

maintainers:
    - name: Friedrich Rober
      url: mailto:friedrich.rober@rwth-aachen.de

GAP: ">= 4.12"

www: https://FriedrichRober.github.io/WPE/
readme: README.md
packageinfo: https://FriedrichRober.github.io/WPE/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/FriedrichRober/WPE/releases/download/v0.2/WPE-0.2.tar.gz

abstract: |

status: dev
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>Rob21</span>]   <b class='BibAuthor'>Rober, F.</b>,
     <i class='BibTitle'>WPE, Provides efficient methods for working with generic wreath products.,
             Version 0.2</i>
     (<span class='BibYear'>2021</span>)<br />
    (<span class='BibNote'>GAP package</span>),
    <span class='BibHowpublished'><a href="https://FriedrichRober.github.io/WPE/">https://FriedrichRober.github.io/WPE/</a></span>.
    </p>
    

bibtex: |
    @misc{ WPE0.2,
      author =           {Rober, F.},
      title =            {{WPE},  Provides efficient methods for working with generic wreath products.,
                          {V}ersion 0.2},
      month =            {Nov},
      year =             {2021},
      note =             {GAP package},
      howpublished =     {\href                                 {https://FriedrichRober.github.io/WPE/}
                          {\texttt{https://FriedrichRober.github.io/}\discretionary
                          {}{}{}\texttt{WPE/}}},
      printedkey =       {Rob21}
    }

