name: WPE
version: "0.5"
license: "GPL-2.0-or-later"
date: 2022-06-17
description: |
    Provides efficient methods for working with wreath product elements.

authors:
    - name: Friedrich Rober
      url: mailto:friedrich.rober@rwth-aachen.de

maintainers:
    - name: Friedrich Rober
      url: mailto:friedrich.rober@rwth-aachen.de

GAP: ">= 4.12"

www: https://FriedrichRober.github.io/WPE/
readme: README.md
packageinfo: https://FriedrichRober.github.io/WPE/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/FriedrichRober/WPE/releases/download/v0.5/WPE-0.5.tar.gz

abstract: |

status: dev
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>Rob22</span>]   <b class='BibAuthor'>Rober, F.</b>,
     <i class='BibTitle'>WPE, Provides efficient methods for working with wreath product elements.,
             Version 0.5</i>
     (<span class='BibYear'>2022</span>)<br />
    (<span class='BibNote'>GAP package</span>),
    <span class='BibHowpublished'><a href="https://FriedrichRober.github.io/WPE/">https://FriedrichRober.github.io/WPE/</a></span>.
    </p>
    

bibtex: |
    @misc{ WPE0.5,
      author =           {Rober, F.},
      title =            {{WPE},  Provides  efficient  methods  for working with
                          wreath product elements., {V}ersion 0.5},
      month =            {Jun},
      year =             {2022},
      note =             {GAP package},
      howpublished =     {\href          {https://FriedrichRober.github.io/WPE/}
                          {\texttt{https://FriedrichRober.github.io/}\discretionary
                          {}{}{}\texttt{WPE/}}},
      printedkey =       {Rob22}
    }

