name: WreathProductElements
version: "0.1"
license: "GPL-2.0-or-later"
date: 2020-04-29
description: |
    Provides efficient methods for working with generic wreath products.

authors:
    - name: Friedrich Rober
      url: mailto:friedrich.rober@rwth-aachen.de

maintainers:
    - name: Friedrich Rober
      url: mailto:friedrich.rober@rwth-aachen.de

GAP: ">= 4.11"

www: https://FriedrichRober.github.io/WreathProductElements/
readme: README.md
packageinfo: https://FriedrichRober.github.io/WreathProductElements/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/FriedrichRober/WreathProductElements/releases/download/v0.1/WreathProductElements-0.1.tar.gz

abstract: |

status: dev
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>Rob20</span>]   <b class='BibAuthor'>Rober, F.</b>,
     <i class='BibTitle'>WreathProductElements, Provides efficient methods for working with generic wreath products.,
             Version 0.1</i>
     (<span class='BibYear'>2020</span>)<br />
    (<span class='BibNote'>GAP package</span>),
    <span class='BibHowpublished'><a href="https://FriedrichRober.github.io/WreathProductElements/">https://FriedrichRober.github.io/WreathProductElements/</a></span>.
    </p>
    

bibtex: |
    @misc{ WreathProductElements0.1,
      author =           {Rober, F.},
      title =            {{WreathProductElements},   Provides  efficient  methods  for  working  with
                          generic wreath products., {V}ersion 0.1},
      month =            {Apr},
      year =             {2020},
      note =             {GAP package},
      howpublished =     {\href             {https://FriedrichRober.github.io/WreathProductElements/}
                          {\texttt{https://FriedrichRober.github.io/}\discretionary
                          {}{}{}\texttt{WreathProductElements/}}},
      printedkey =       {Rob20}
    }

