name: CI

# Trigger the workflow on push or pull request
on:
  push:
    branches: ['master']
  pull_request:

jobs:
  # The CI test job
  test:
    name: ${{ matrix.gap-branch }} - HPCGAP ${{ matrix.HPCGAP }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        gap-branch:
          - master
        HPCGAP: ['no']

    steps:
      - uses: fkirc/skip-duplicate-actions@master
      - uses: actions/checkout@v2
      - uses: gap-actions/setup-gap@v2
        with:
          GAPBRANCH: ${{ matrix.gap-branch }}
          HPCGAP: ${{ matrix.HPCGAP }}
      - uses: gap-actions/build-pkg@v1
      - uses: gap-actions/build-pkg-docs@v1
      - uses: gap-actions/run-pkg-tests@v2
      - uses: gap-actions/process-coverage@v2
      - uses: codecov/codecov-action@v2

  # The documentation job
  manual:
    name: Build manuals
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: gap-actions/setup-gap@v2
      - uses: gap-actions/build-pkg-docs@v1
        with:
          use-latex: 'true'
      - name: 'Upload documentation'
        uses: actions/upload-artifact@v2
        with:
          name: manual
          path: ./doc/manual.pdf

